# Generated by Django 5.2.17 on 2026-08-14 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('path_photo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho da Foto')),
                ('password', models.CharField(max_length=255, verbose_name='Senha Hash')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nome de Usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Usuário do App',
                'verbose_name_plural': 'Usuários do App',
                'db_table': 'user_app',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('path_photo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho da Foto')),
                ('password', models.CharField(max_length=255, verbose_name='Senha Hash')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nome de Usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Gerente',
                'verbose_name_plural': 'Gerentes',
                'db_table': 'user_manager',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cnpj', models.CharField(db_index=True, max_length=20, verbose_name='CNPJ')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Telefone de Contato')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nome do Restaurante')),
                ('address', models.TextField(verbose_name='Endereço Completo')),
                ('site', models.URLField(blank=True, max_length=255, null=True, verbose_name='Site Oficial')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Perfil do Instagram')),
                ('path_logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do Logo')),
                ('manager', models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='main.usermanager', verbose_name='Gerente Responsável')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'db_table': 'restaurant',
                'ordering': ['-created_at'],
            },
        ),
    ]
