# Generated by Django 5.2.17 on 2026-08-24 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermanager",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Administrador"),
        ),
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("WEB", "Site Web"),
                            ("APP", "Aplicativo Mobile"),
                            ("BOTH", "Ambos"),
                        ],
                        max_length=10,
                        verbose_name="Plataforma Afetada",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BUG", "Bug"),
                            ("SUPPORT", "Suporte"),
                            ("IMPROVEMENT", "Melhoria"),
                        ],
                        default="BUG",
                        max_length=15,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberto"),
                            ("IN_PROGRESS", "Em Andamento"),
                            ("RESOLVED", "Resolvido"),
                            ("CLOSED", "Fechado"),
                        ],
                        default="OPEN",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Resposta do Admin"
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        db_column="opened_by_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bug_reports",
                        to="main.usermanager",
                        verbose_name="Aberto por",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="resolved_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to="main.usermanager",
                        verbose_name="Resolvido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chamado",
                "verbose_name_plural": "Chamados",
                "db_table": "bug_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberta"),
                            ("CLOSED", "Fechada"),
                            ("PAUSED", "Pausada"),
                        ],
                        default="CLOSED",
                        max_length=10,
                        verbose_name="Status da Fila",
                    ),
                ),
                (
                    "current_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tamanho Atual da Fila"
                    ),
                ),
                (
                    "estimated_wait_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tempo de Espera Estimado (minutos)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        db_column="restaurant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue",
                        to="main.restaurant",
                        verbose_name="Restaurante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fila",
                "verbose_name_plural": "Filas",
                "db_table": "queue",
                "ordering": ["-updated_at"],
            },
        ),
    ]
