# Generated by Django 5.2.17 on 2026-08-30 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_usermanager_is_admin_bugreport_queue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Categoria"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descrição"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome do Item")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="main.category",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Categoria",
                "verbose_name_plural": "Itens de Categoria",
                "db_table": "category_item",
                "ordering": ["category", "name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.AddField(
            model_name="restaurant",
            name="category_items",
            field=models.ManyToManyField(
                blank=True,
                related_name="restaurants",
                to="main.categoryitem",
                verbose_name="Categorias do Restaurante",
            ),
        ),
        migrations.AddField(
            model_name="userapp",
            name="preferences",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="main.categoryitem",
                verbose_name="Preferências",
            ),
        ),
    ]
