# Generated by Django 5.2.17 on 2026-09-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_add_category_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
