# Generated by Django 5.2.17 on 2026-09-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_add_lat_lng_to_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
