# Generated by Django 5.2.17 on 2026-09-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_chat_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="current_tables",
            field=models.PositiveIntegerField(default=0, verbose_name="Mesas ocupadas"),
        ),
        migrations.AddField(
            model_name="queue",
            name="max_capacity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Capacidade máxima de pessoas"
            ),
        ),
        migrations.AddField(
            model_name="queue",
            name="max_tables",
            field=models.PositiveIntegerField(default=0, verbose_name="Total de mesas"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="queue",
            name="current_size",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Pessoas na fila"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
