# Generated by Django 5.2.17 on 2026-09-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_add_description_queue_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="chat_last_reset_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Último reset do chat"
            ),
        ),
    ]
