# Generated by Django 5.2.17 on 2026-09-16 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_add_chat_reset_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "guest_name",
                    models.CharField(max_length=200, verbose_name="Nome do Cliente"),
                ),
                (
                    "guest_phone",
                    models.CharField(max_length=30, verbose_name="Telefone do Cliente"),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        blank=True, max_length=255, verbose_name="E-mail do Cliente"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data da Reserva")),
                ("time", models.TimeField(verbose_name="Hora da Reserva")),
                (
                    "party_size",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Número de Pessoas"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("CONFIRMED", "Confirmada"),
                            ("CANCELLED", "Cancelada"),
                            ("COMPLETED", "Concluída"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="main.restaurant",
                        verbose_name="Restaurante",
                    ),
                ),
                (
                    "user_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="main.userapp",
                        verbose_name="Usuário (se cadastrado)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "db_table": "reservation",
                "ordering": ["date", "time"],
            },
        ),
    ]
