# Generated by Django 5.2.17 on 2026-09-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_add_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="checked_in_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Check-in em"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("CONFIRMED", "Confirmada"),
                    ("CHECKED_IN", "Check-in realizado"),
                    ("CANCELLED", "Cancelada"),
                    ("COMPLETED", "Concluída"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
